default_platform(:ios)
 
platform :ios do
  desc "Upload IPA to App Store"
  lane :upload do
    deliver(
      ipa: "release/AnxinSpace_4.0.3.1001_20250715100310_resign.ipa",
      force: true, # 覆盖已存在的版本
      skip_metadata: true, # 跳过元数据上传
      skip_screenshots: true, # 跳过截图上传
      submit_for_review: false, # 不提交审核（仅上传 IPA）
      run_precheck_before_submit: false, # 禁用预检查
      team_id: ENV["APP_STORE_CONNECT_TEAM_ID"],
      api_key: app_store_connect_api_key(
        key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
        issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
        key_content: ENV["APP_STORE_CONNECT_API_PRIVATE_KEY"],
        in_house: false # 非企业账号设为 false
      )
    )
  end
end
